
project_id = "eppgmfcebxhjsyhosxtm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://127.0.0.1:54321"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
site_url = "http://127.0.0.1:3000"
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
image_transformation.enabled = true

[functions.get-secret]
verify_jwt = false

[functions.post-to-facebook]
verify_jwt = false

[functions.facebook-auth-url]
verify_jwt = false

[functions.facebook-exchange-code]
verify_jwt = false

[functions.post-to-farcaster]
verify_jwt = false

[functions.post-to-lens]
verify_jwt = false

[functions.post-to-twitter]
verify_jwt = false

[functions.post-to-tiktok]
verify_jwt = false

[functions.process-scheduled-posts]
verify_jwt = false

[functions.schedule-post]
verify_jwt = false

[functions.tiktok-auth-url]
verify_jwt = false

[functions.tiktok-exchange-code]
verify_jwt = false

[functions.verify-tiktok-secrets]
verify_jwt = false

[edge-runtime]
policy = "per_worker"
inspector_port = 8083

[db]
port = 54322
shadow_port = 54320
major_version = 15
