
project_id = "eppgmfcebxhjsyhosxtm"
[functions.post-to-twitter]
verify_jwt = true
[functions.post-to-lens]
verify_jwt = true
[functions.post-to-farcaster]
verify_jwt = true
[functions.schedule-post]
verify_jwt = true
[functions.process-scheduled-posts]
verify_jwt = true
