// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eppgmfcebxhjsyhosxtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwcGdtZmNlYnhoanN5aG9zeHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTMwMjYsImV4cCI6MjA2MDM4OTAyNn0.WXymdCloDSNwlD4QrOoxxDyzXU4-vD6VS_RgfHErLqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);